project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^detail_view/(?P<pk>\d+)/$', 'main.views.detail_view'),
    url(r'^list_view/$', 'main.views.list_view'),

    url(r'^cereal_types/$', 'main.views.cereal_types'),
    url(r'^cereal_details/(?P<pk>\d+)/$', 'main.views.cereal_details'),
    url(r'^brand/$', 'main.views.brands'),
    url(r'^brand_details/(?P<pk>\d+)/$', 'main.views.brand_details'),
    url(r'^$', 'main.views.main_page'),

    
    url(r'^create_view/$','main.views.create_view'),
    url(r'^create_view2/$','main.views.create_view2'),

    url(r'^json_response/$', 'main.views.json_response'),
    url(r'^ajax_template/$', 'main.views.ajax_search'),

    #url(r'^update_view/(?P<pk>\d+)/$', 'main.view.update_view'),
    #url(r'^delete_view/(?P<pk>\d+)/$', 'main.view.delete_view'),

    #url(r'^signup/$', 'main.view.signup'),
    #url(r'^login_view/$', 'main.view.login_view'),
    #url(r'^logout_view/$', 'main.views.logout_view'),

    #url(r'^', include('project.urls')),
    #url(r'^cereals/$', views.cereal_list),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns = format_suffix_patterns(urlpatterns)

main/models.py
from django.db import models
from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles


class Manufacturer(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True) 

    def __unicode__(self):
        return self.name


class Cereal(models.Model):
    cereal_name = models.CharField(max_length=200, null=True, blank=True)
    manufacturer = models.ForeignKey(Manufacturer, null=True, blank=True)
    calories = models.IntegerField(null=True, blank=True)
    protein = models.IntegerField(null=True, blank=True)
    fat = models.IntegerField(null=True, blank=True)
    sodium = models.IntegerField(null=True, blank=True)
    dietary_fiber = models.FloatField(null=True, blank=True)
    carbs = models.FloatField(null=True, blank=True)
    sugars = models.IntegerField(null=True, blank=True)
    potassium = models.IntegerField(null=True, blank=True)
    vitamins_and_minerals = models.IntegerField(null=True, blank=True)

    # class Meta:
         #ordering = ('created',)

    def __unicode__(self):
        return self.cereal_name

main/forms.py
from main.models import Manufacturer


class ManufacturerForm(forms.ModelForm):  
    class Meta:
        model = Manufacturer
        fields = '__all__'

# #class SpeedModelForm2(forms.Form):  
#     title = forms.CharField(required=True)
#     info = forms.CharField(required=True, widget=forms.Textarea)
#     image = forms.ImageField(required=True)

class ManufacturerForm2 (form.Form):
    title = forms.CharField(required=True)
    info = forms.CharField(required=True, widget=forms.Textarea)
    image = forms.ImageField(required=True)


#class SpeedModelUpdateForm(forms.Form):  
    title = forms.CharField(required=False)
    info = forms.CharField(required=False, widget=forms.Textarea)
    image = forms.ImageField(required=False)

# #class UserSignUp(forms.Form):  
#     email = forms.EmailField(required=True)
#     password = forms.CharField(widget=forms.PasswordInput(), required=True)

# #class UserLogin(forms.Form):  
#     username = forms.CharField(required=True)
#     password = forms.CharField(required=True, widget=forms.PasswordInput())

main/views.py
from django.shortcuts import render, render_to_response
from django.contrib.auth import authenticate, login, logout
from main.models import Manufacturer, Cereal
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect #JsonResponse 

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
#from cereal.serializers import CerealSerializer


def ajax_search(request):
    context = {}

    return render_to_response('ajax_template.html', context, context_instance=RequestContext(request))


@api_view(['GET', 'POST'])
def cereal_list(request):
#def json_response(request):

    if request.method == 'GET':
        cereals = Cereal.objects.all()
        serailizer = CerealSerializer(cereals, many=True)
        return Response(serializer.data)

    elif request.method == "POST":
        serializer = CerealSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    # #search_string = request.GET.get('search', '')

    # objects = Cereal.objects.filter(cereal_name__icontains=search_string)

    # object_list = []

    # for obj in objects:
    #     object_list.append(obj.cereal_name)

    # return JsonResponse(object_list, safe=False)


def cereal_details(request, pk):

    context = {}

    cereal = Cereal.objects.get(pk=pk)

    context['cereal'] = cereal

    return render_to_response('cereal_details.html', context, context_instance=RequestContext(request))


def main_page(request):

    context = {}

    return render_to_response('main_page.html', context, context_instance=RequestContext(request))


def cereal_types(request):

    cereals = Cereal.objects.all()

    context = {}

    context['cereals'] = cereals

    return render_to_response('cereal_types.html', context, context_instance=RequestContext(request))


def brands(request):

    makers = Manufacturer.objects.all()

    context = {}

    context['makers'] = makers

    
    return render_to_response('brands.html', context, context_instance=RequestContext(request))


def brand_details(request, pk):

    context = {}

    maker = Manufacturer.objects.get(pk=pk)

    context['maker'] = maker


    return render_to_response('brand_details.html', context, context_instance=RequestContext(request))


def detail_view(request, pk):

    makers = Manufacturer.objects.all()

    cereals = Cereal.objects.all()

    context = {}

    context['makers'] = makers

    context['cereals'] = cereals

    return render_to_response('detail_view.html', context, context_instance=RequestContext(request))


def list_view(request):

    makers = Manufacturer.objects.all()

    cereals = Cereal.objects.all()

    context = {}

    context['makers'] = makers

    context['cereals'] = cereals

    return render_to_response('list_view.html', context, context_instance=RequestContext(request))


def create_view(request):
    context = {} 
    form = MakerForm()
    context['form'] = form

    if request.method == 'POST':
            form = MakerForm(request.POST, request.FILES)

            if form.is_valid():
                print form.is_valid()

                form.save()
                return HttpResponseRedirect('/list_view/')
            else:
                context['errors'] = form.errors

    return render_to_response('create_view1.html', context, context_instance=RequestContext(request))
    #  #context = {}

    # context['request'] = request.method

    # context['Manufacturer'] = Manufacturer.objects.all()

    # if request.method == 'POST':
    #     form = ManufacturerForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         print form.is_valid()

    #         form.save()
    #         return HttpResponseRedirect('/list_view/')
    #     else:
    #         context['errors'] = form.errors
    # return render_to_response('create_view.html', context, context_instance=RequestContext(request))


def create_view2(request):
     context = {}

     form = MakerForm2()
     context['form'] = form

     #if request.method == 'POST':
    #     form = SpeedModelForm2(request.POST, request.FILES)

    #     if form.is_valid():

    #         print form.cleaned_data

    #         title = form.cleaned_data['title']
    #         info = form.cleaned_data['info']
    #         image = form.cleaned_data['image']

    #         new_object = SpeedModel()

    #         new_object.title = title
    #         new_object.info = info
    #         new_object.image = image

    #         new_object.save()

    #         return HttpResponseRedirect('/list_view/')
    #     else:
    #         context['errors'] = form.errors

    # return render_to_response('create_view2.html', context, context_instance=RequestContext(request))


    # #context = {}

    # context['request'] = request.method

    # context['Manufacturer'] = Manufacturer.objects.all()

    # if request.method == "POST":
    #     cereal_name = request.GET.get('Cereal Name', None)
    #     manufacturer = request.GET.get('Manufacturer', None)
    #     protein = request.GET.get('Protein', None)
    #     fat = request.GET.get('Fat', None)
    #     sodium = request.POST.get('Sodium', None)
    #     dietary_fiber = request.POST.get('Dietary Fiber', None)
    #     carbs = request.POST.get('Carbs', None)
    #     sugars = request.POST.get('Sugars', None)
    #     postassium = request.POST.get('Potassium', None)
    #     vitamins_and_minerals = request.POST.get('Vitamins and Minerals', None)

    #     # #if != None:
    #     #     state = State.objects.get(pk=state_id)
    #     # else:
    #     #     state = State.objects.get(name="Texas")

    #     the_create_view, created = Manufacturer.objects.get_or_create(name=cereal_name)

    #     the_create_view.protein = protein
    #     the_create_view.fat = fat 
    #     the_create_view.sodium = sodium 
    #     the_create_view.dietary_fiber = dietary_fiber
    #     the_create_view.carbs = carbs
    #     the_create_view.sugars = sugars
    #     the_create_view.postassium = postassium
    #     the_create_view.vitamins_and_minerals = vitamins_and_minerals

    #     the_create_view.save()

    #     context['created'] = "Operation Successful"

    # elif request.method == 'GET':
    #     pass

    # return render_to_response('create_view.html', context, context_instance=RequestContext(request))




def update_view(request, pk):

    # #context = {}

    # speed_object = SpeedModel.objects.get(pk=pk)

    # context['speed_object'] = speed_object

    # form = SpeedModelUpdateForm()

    # context['form'] = form

    # if request.method == 'POST':
    #     form = SpeedModelUpdateForm(request.POST, request.FILES)

    #     if form.is_valid():
    #         speed_object.title = form.cleaned_data['title']
    #         speed_object.info = form.cleaned_data['info']

    #         if form.cleaned_data['image'] != None:
    #             speed_object.image = form.cleaned_data['image']

    #         speed_object.save()

    #         return HttpResponseRedirect('/update_view/%s/' % pk)

    #     else:
    #         context['errors'] = form.errors

    # return render_to_response('update_view.html', context, context_instance=RequestContext(request))
    # maker = Manufacturer.objects.get(pk=pk)

    # context = {}

    context['maker'] = maker 

    return render_to_response('update_view.html', context, context_instance=RequestContext(request))


def delete_view(request, pk):
    pass
    # #SpeedModel.objects.get(pk=pk).delete()

    # return HttpResponseRedirect('/list_view/')
    # maker = Manufacturer.objects.get(pk=pk)

    # context = {}

    # context['maker'] = maker 

    # return render_to_response('delete_view.html', context, context_instance=RequestContext(request))


# #def signup(request):

#     context = {}

#     form = UserSignUp()
#     context['form'] = form

#     if request.method == 'POST':
#         form = UserSignUp(request.POST)
#         if form.is_valid():
#             print form.cleaned_data

#             name = form.cleaned_data['name']
#             email = form.cleaned_data['email']
#             password = form.cleaned_data['password']

#             try:
#                 new_user = User.objects.create_user(name, email, password)
#                 context['valid'] = "Thank You For Signing Up!"

#                 auth_user = authenticate(username=name, password=password)
#                 login(request, auth_user)

#                 return HttpResponseRedirect('/list_view/')

#             except IntegrityError, e:
#                 context['valid'] = "A User With That Name Already Exists"

#         else:
#             context['valid'] = form.errors

#     if request.method == 'GET':
#         context['valid'] = "Please Sign Up!"

#     return render_to_response('signup.html', context, context_instance=RequestContext(request))




# #def login_view(request):

#     # #context = {}

#     # context['form'] = UserLogin()

#     # username = request.POST.get('username', None)
#     # password = request.POST.get('password', None)

#     # auth_user = authenticate(username=username, password=password)

#     # if auth_user is not None:
#     #     if auth_user.is_active:
#     #         login(request, auth_user)
#     #         context['valid'] = "Login Successful"

#     #         return HttpResponseRedirect('/home/')
#     #     else:
#     #         context['valid'] = "Invalid User"
#     # else:
#     #     context['valid'] = "Please enter a User Name"


#     # return render_to_response('login_view.html', context, context_instance=RequestContext(request))

#     # maker = Manufacturer.objects.get(pk=pk)

#     context = {}

#     context['maker'] = maker 

main/templates/ajax_template.html
<!DOCTYPE html>  
<html>  
<head>  
        <title>Cereal List</title>

</head>  
    <body>

    <input id='test-input' type='text'></input>

    <p id='output'></p>

    </br>

    <p id='clickme-js'>Click Me JS</p>
    <p id='clickme-jq'>Click Me JQ</p>
    <ul id='list'>
        <li class="list-element">Item 1</li>
        <li class="list-element">Item 2</li>
        <li class="list-element">Item 3</li>
        <li class="list-element">Item 4</li>
    </ul>

    </body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
    <script type="text/javascript">

        $('#test-input').on('keyup', function(){
            $.ajax({
                type: 'GET',
                url: '/json_response/',
                data: { search: $('#test-input').val()},
                error: function(){
                    //What to do if there is an error

                },
                success: function(data){
                    console.log(data[0]);

                    for(i=0; i < data.length; i++){

                    $('#output').append('<li>' + data[i] + '</li>');
                    }
                }



            });

        });


        $('#clickme-jq').on('click', function(){
            $('#list').append('<li>JQ ELement</li>');

        });


        document.getElementById('clickme-js').addEventListener('click', function(){
        ul = document.getElementById('list');
        li = document.createElement('li');
        li.appendChild(document.createTextNode('JS Element'));
        ul.appendChild(li);



    });

    </script>
</html>  

main/templates/base.html
<!--Contains information that we will want to repeat in all other templates.--> 

{% load static from staticfiles %}


<!DOCTYPE html>  
<html>  
<head>  
    <title>{% block title %}{% endblock %}</title>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/mystyle.css' %}" rel="stylesheet"/>

</head>  
    <body>
<!-- we are in cereal_list.html -->  
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
           
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar">What do you do</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li class="links"><a href="/">Homepage </a></li>
                                <li class="links"> <a href="/cereal_types/{{container.pk}}">Cereal List </a> </li>
                                <li class="links"><a href="/brand/">Cereal Brands </a></li>
                            </ul>
                        </div>
                    <!-- /.navbar-collapse -->
                    </div>
                </div>
          </div>
    </nav>
{% block body%}






{% endblock body %}
    <!-- Page Content -->
            <br>
            <br>
        <div class="background-color">
            <div class="background_image">
                <img src="https://upload.wikimedia.org/wikipedia/commons/f/fc/Froot-Loops-Cereal-Bowl.jpg">  
            </div>
        </div>
        
        <!-- /.row -->

   
    <!-- /.container -->

    <!-- jQuery Version 1.11.1 -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static '//code.jquery.com/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static '//code.jquery.com/jquery-migrate-1.2.1.min.js' %}"></script>
    <script type="text/javascript">
       $(document).click(function(){
            $('img').toggle("explode");

        // //$(".navbar-nav").on('click', function(){
        //     $('.links').append('<li>Make a List</li>');


        });




       });
        
  

            
            

            



      

        // //$('#cereals').on( 'mouseenter', function(e){
        //     if(e.target.id){
        //         ${'#'+e.target.id).children().fadeIn();

        //     }


       
         
    </script>
</body>
</html>  

main/templates/brand_details.html
{% extends 'base.html' %}


{% block body%}

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-ms-12 col-xs-12">
                <br>
                <br>
            <div class="long_list">
                {% for cereal in maker.cereal_set.all %}
                    <h2>{{cereal}}</h2>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock body%}

main/templates/brands.html
{% extends 'base.html' %}
{% block body %} 

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <br>
                <br>
                <br>
            <div class="long_list">
                {% for manufacturer in makers %}
                    <a href="/brand_details/{{ manufacturer.pk }}/">{{manufacturer.name}}</a>
                    <br>

                {% endfor %}

            <br>
            <div class="homepage">
                <a href="/"/> ~ Homepage ~</a>
                <h3>{{manufacturer.name}}</h3>
            </div>
        
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/cereal_details.html
{% extends 'base.html' %}
{% block body%}

<div class="container">
    <div class="row">
        <div class="col-12-6 col-md-6 col-sm-6 col-xs-6">
            <br>
            <br>
            <br>
            

        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="cereal_name">
                <h2>{{cereal.cereal_name}} </h2></a>
            </div>

            <br>
            <br>

                <ul id="nutrition">
                    <li>Calories: {{cereal.calories}}</li>
                    <li>Protein: {{cereal.protein}}</li>
                    <li>Fat: {{cereal.fat}}</li>
                    <li>Sodium: {{cereal.sodium}}</li>
                    <li>Dietary Fiber: {{cereal.dietary_fiber}}</li>
                    <li>Carbohydrates: {{cereal.carbs}}</li>
                    <li>Sugar: {{cereal.sugars}}</li>
                    <li>Potassium: {{cereal.potassium}}</li>
                    <li>Vitamins and Minerals: {{cereal.vitamins_and_minerals}}</li>
                </ul>
                
        </div>
    </div>
</div>
{% endblock %}

main/templates/contact.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - Contact</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="post.html">Sample Post</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('img/contact-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>

main/templates/create_view.html
def create_view1(request):

    context = {} 
    form = SpeedModelForm()
    context['form'] = form

    if request.method == 'POST':
        form = SpeedModelForm(request.POST, request.FILES)
        if form.is_valid():
            print form.is_valid()

            form.save()
            return HttpResponseRedirect('/list_view/')
        else:
            context['errors'] = form.errors
    return render_to_response('create_view1.html', context, context_instance=RequestContext(request))

main/templates/create_view2.html
{% extends 'base.html' %}

{% block body %}

    <form action="/create_view2/" enctype="multipart/form-data" method="POST" >

        {% comment %}
            csrf_token is a randomly generated string of text that the server uses to confirm that the form was creaed by the django server and not a 3rd party / outside website, application or other data source.
        {% endcomment %}
        {% csrf_token %}    

        {{ form.as_p }}

        <input type="submit" value="Create Object" />

    </form>

{% endblock %}

main/templates/detail_view.html
{% extends 'base.html' %}


{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">

{% for container in maker.cereal_set.all %}
    {{ container }}
    {{ forloop.counter }}
    <a href="/list_view/{{container.pk}}">{{container.cereal_name}}</a>
    <br>

{% endfor %}
        </div>
    </div>

<br>
<a href="/list_view"/> Back to Manufacturer</a>
<h3>{{manufacturer.name}}</h3>

{% for container in cereals.cereal_set.all %}
    {{container}}
    {{forloop.counter}}
    <a href="/brand/{{container.pk}}">{{container.cereal_name}}</a>
{% endfor %}
<br>
<a href="/cereal_types/"/> Back to Cereal </a>
<h3>{{manufacturer.cereal_name}}</h3>

</div>
{% endblock %}

main/templates/login_view.html
{% extends 'base.html' %}

{% block body %}

    <form action='/login_view/' method="POST">

        {% csrf_token %}

        {{ form.as_p }}

        <input type='submit' value='Login In' />

    </form>

{% endblock %}

main/templates/main_page.html
{% extends 'base.html'%}
{% load static from staticfiles %}


{% block body %}

    



{% endblock body%}